#include "backends/QEMUBackend.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Constants.h"
#include "llvm/Support/raw_ostream.h"
#include <fstream>
#include <algorithm>
#include <cstdio>

//Impelment helpder function
// "mangoboost,uart-v2" -> "MangoboostUartV2"
std::string QEMUBackend::makeTypeName(const std::string& compatible) {
  std::string result;
  bool capNext = true;
  for (char c : compatible) {
    if (!std::isalnum(c)) { capNext = true; continue; }
    result += capNext ? (char)std::toupper(c) : c;
    capNext = false;
  }
  return result;
}
//mangoboost,uart-v2 -> MANGOBOOST_UART_V2
std::string QEMUBackend::makeUpperName(const std::string& compatible) {
  std::string s = compatible;
  for (auto& c : s)
    c = std::isalnum(c) ? (char)std::toupper(c) : '_';
  return s;
}
// "mangoboost,uart-v2" -> "mangoboostuart_v2"
std::string QEMUBackend::makeMacroName(const std::string& compatible) {
  std::string s = compatible;
  for (auto& c : s)
    c = std::isalnum(c) ? (char)std::tolower(c) : '_';
  return s;
}

//Read IR Metadata
static std::string getMDStr(llvm::MDNode* n, unsigned i) {
  if(!n || i >= n->getNumOperands()) return "";
  auto* s = llvm::dyn_cast<llvm::MDString>(n->getOperand(i));
  return s ? s->getString().str() : "";
}

static int32_t getMDI32(llvm::MDNode* n, unsigned i) {
  if(!n || i >= n->getNumOperands()) return 0;
  auto* c = llvm::dyn_cast<llvm::ConstantAsMetadata>(n->getOperand(i));
  if(!c) return 0;
  return (int32_t)llvm::cast<llvm::ConstantInt>(c->getValue())->getZExtValue();
}

std::string QEMUBackend::readCompatible() {
  auto* NMD = M.getNamedMetadata("ip.def");
  if(!NMD || NMD->getNumOperands() == 0) return "unknown";
  return getMDStr(NMD->getOperand(0),0);
}

std::vector<QEMUBackend::RegInfo> QEMUBackend::readRegmaps() {
  std::vector<RegInfo> regs;
  auto* NMD = M.getNamedMetadata("ip.regmaps");
  if (!NMD) return regs;

  for (unsigned i = 0; i < NMD->getNumOperands(); i++) {
    auto* node = NMD->getOperand(i);
    RegInfo r;
    r.name = getMDStr(node,0);
    r.offset     = (uint32_t)getMDI32(node, 1);
    r.size       = (uint32_t)getMDI32(node, 2);
    r.access     = getMDStr(node, 3);
    r.resetValue = (uint32_t)getMDI32(node, 4);
    regs.push_back(r);
  }
  return regs;
}

uint32_t QEMUBackend::calcMemRegionSize(const std::vector<RegInfo>& regs) {
  if(regs.empty()) return 0x1000; //Default 4KB
  auto& last = regs.back();
  uint32_t end = last.offset + last.size;
  //Ceiling 4KB
  return (end+0xFFF) & ~0xFFFu;
}

//Generate Header
void QEMUBackend::emitHeaderTop(std::ostream& os, const std::string& compatible, const std::string& guard, const std::string& typeName) {
    os << "// AUTO-GENERATED by ip-tool (QEMUBackend)\n";
    os << "// compatible: " << compatible << "\n";
    os << "// DO NOT EDIT — fill in hook implementations\n\n";
    os << "#pragma once\n";
    os << "#ifndef " << guard << "_QEMU_H\n";
    os << "#define " << guard << "_QEMU_H\n\n";
    os << "#include \"qemu/osdep.h\"\n";
    os << "#include \"hw/sysbus.h\"\n";
    os << "#include \"" << makeMacroName(compatible)
       << "_reg.h\"\n\n";
}