#include "backends/RegHeaderBackend.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Constants.h"
#include "llvm/ADT/StringRef.h"
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cstdint>

//Implement helper function
//"mangoboost,uart-v2" -> "MANGOBOOST_UART_V2_H"
std::string RegHeaderBackend::makeGuard(const std::string& compatible) {
  std::string g = compatible;
  std::transform(g.begin(), g.end(), g.begin(), ::toupper);
  for(auto&c : g)
    if(!std::isalnum(c)) c = '_';
  return g+"_H";
}

//"mangoboost,uart-v2" -> mangoboost_uart_v2
std::string RegHeaderBackend::makeStructName(const std::string& compatible) {
  std::string s = compatible;
  for (auto& c : s)
    if(!std::isalnum(c)) c = '_';
  return s;
}

//[lo:hi] bitmask
uint32_t RegHeaderBackend::fieldMask(int lo, int hi) {
    int width = hi - lo + 1;
    if (width >= 32) return 0xFFFFFFFF;
    return ((1u << width) - 1u);
}

//Helper for Metadata read
//read string from MDNode
static std::string getMDString(llvm::MDNode* node, unsigned idx) {
  if(!node || idx >= node->getNumOperands()) return "";
  auto* mds = llvm::dyn_cast<llvm::MDString>(node->getOperand(idx));
  return mds ? mds->getString().str() : "";
}
//read i32 from MDNode
static int32_t getMDInt32(llvm::MDNode* node, unsigned idx) {
  if(!node || idx >= node -> getNumOperands()) return 0;
  auto* cmd = llvm::dyn_cast<llvm::ConstantAsMetadata>(node->getOperand(idx));
  if(!cmd) return 0;
  return (int32_t)llvm::cast<llvm::ConstantInt>(cmd->getValue())->getZExtValue();
}
//Implement method
//Read compatible
std::string RegHeaderBackend::readCompatible() {
  auto* NMD = M.getNamedMetadata("ip.def");
  if (!NMD || NMD->getNumOperands() == 0) return "unknown";
  return getMDString(NMD->getOperand(0),0);
}
//Emit section
void RegHeaderBackend::emitFileHeader(std::ostream& os, const std::string& compatible, const std::string& guard) {
  os<<"// AUTO-GENERATED by compiler\n";
  os<<"// compatible: "<<compatible<<"\n";
  os<<"// DO NOT EDIT\n";
  os<<"#pragma once\n";
  os<<"#ifndef "<<guard<<"\n";
  os<<"#define "<<guard<<"\n";
  os<<"#include <stdint.h>\n";
  os<<"\n";
}
void RegHeaderBackend::emitOffset(std::ostream& os) {
  auto* NMD = M.getNamedMetadata("ip.regmaps");
  if(!NMD) return;
  os<<"/* -- Register offsets";
  os<<" -- */\n";

  for(unsigned i = 0; i < NMD->getNumOperands(); ++i) {
    auto* reg = NMD->getOperand(i);
    std::string label = getMDString(reg,0);
    int32_t offset = getMDInt32(reg,1);

    // REG_LABEL_OFFSET 0xXXXXU
    os<<"#define "<<label<<"_OFFSET"
      <<" 0x"
      << std::hex << std::uppercase;
    // 4 hex
    char buf[16];
    std::snprintf(buf, sizeof(buf), "%04X", (uint32_t)offset);
    os<<buf<<"U\n";
  }
  os <<std::dec; //Release Hex mode
  os <<"\n";
}

void RegHeaderBackend::emitFields(std::ostream& os) {
  auto* NMD = M.getNamedMetadata("ip.regmaps");
  if(!NMD) return;
  for(unsigned i = 0; i < NMD->getNumOperands(); i++) {
    auto* reg = NMD->getOperand(i);

    std::string label = getMDString(reg,0);
    int32_t offset = getMDInt32(reg, 1);
    std::string access = getMDString(reg,3);
    int32_t reset = getMDInt32(reg,4);
    
    //Section header
    char buf[64];
    std::snprintf(buf, sizeof(buf), "0x%08X", (uint32_t)reset);
    os<<"/* -- "<<label<<" ("<<access<<", reset="<<buf<<") ";
    os<<"-- */\n";
    //Field list
    if(reg->getNumOperands() <= 5) { os<<"\n"; continue; }
    auto* fieldList = llvm::dyn_cast<llvm::MDNode> (reg->getOperand(5));
    if(!fieldList) { os <<"\n"; continue; }
    for(unsigned j = 0; j < fieldList->getNumOperands(); ++j) {
      auto* field = llvm::dyn_cast<llvm::MDNode>(fieldList->getOperand(j));
      if(!field) continue;

      std::string fname = getMDString(field,0);
      int32_t lo = getMDInt32(field, 1);
      int32_t hi = getMDInt32(field, 2);
      std::string desc = getMDString(field, 3);
      uint32_t mask = fieldMask(lo,hi);

      std::string prefix = label + "_" + fname;
      
      // _POS
      os << "#define " << prefix << "_POS"
          << "  " << lo << "U"
          << "  /* [" << hi << ":" << lo << "] "
          << desc << " */\n";

      // _MSK
      char maskBuf[16];
      std::snprintf(maskBuf, sizeof(maskBuf),
          "0x%XU", mask);
      os << "#define " << prefix << "_MSK"
         << "  (" << maskBuf
         << " << " << prefix << "_POS)\n";
      //Add SET/GET macro for non-single field
      if (lo != hi) {
          os << "#define " << prefix << "_SET(v)"
             << "  (((v) & " << maskBuf << ")"
             << " << " << prefix << "_POS)\n";
          os << "#define " << prefix << "_GET(r)"
             << "  (((r) >> " << prefix << "_POS)"
             << " & " << maskBuf << ")\n";
      }
    }
    os <<"\n";
  }
}
void RegHeaderBackend::emitAccessors(std::ostream& os) {
    os << "/* -- Register Accessors ";
    os << "-- */\n";
    os << "#define IP_REG_READ(base, off) \\\n";
    os << "    (*((volatile uint32_t*)"
       << "((uintptr_t)(base) + (off))))\n";
    os << "#define IP_REG_WRITE(base, off, val) \\\n";
    os << "    (*((volatile uint32_t*)"
       << "((uintptr_t)(base) + (off)))"
       << " = (uint32_t)(val))\n";
    os << "#define IP_REG_MODIFY(base, off, msk, val) \\\n";
    os << "    IP_REG_WRITE(base, off, \\\n";
    os << "        (IP_REG_READ(base, off) & ~(msk))"
       << " | ((val) & (msk)))\n";
    os << "\n";
}

void RegHeaderBackend::emitRegMapStruct(std::ostream& os) {
    auto* NMD = M.getNamedMetadata("ip.regmaps");
    if (!NMD) return;

    std::string compatible = readCompatible();
    std::string structName = makeStructName(compatible);

    os << "/* -- Register Map Struct ";
    os << "-- */\n";
    os << "typedef struct {\n";

    uint32_t cursor = 0;
    int      padIdx = 0;

    for (unsigned i = 0; i < NMD->getNumOperands(); ++i) {
        auto* reg = NMD->getOperand(i);

        std::string label  = getMDString(reg, 0);
        uint32_t    offset = (uint32_t)getMDInt32(reg, 1);
        uint32_t    size   = (uint32_t)getMDInt32(reg, 2);
        std::string access = getMDString(reg, 3);
        uint32_t    reset  = (uint32_t)getMDInt32(reg, 4);

        if (offset > cursor) {
            uint32_t gap = (offset - cursor) / 4;
            os << "    volatile uint32_t _pad"
               << padIdx++ << "[" << gap << "];\n";
        }

        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "/* 0x%04X %s reset=0x%08X */",
            offset, access.c_str(), reset);

        os << "    volatile uint32_t "
           << label << ";  " << buf << "\n";

        cursor = offset + size;
    }

    os << "} " << structName << "_RegMap_t;\n";
    os << "\n";
}

void RegHeaderBackend::emitFileFooter(std::ostream& os,
        const std::string& guard) {
    os << "#endif /* " << guard << " */\n";
}

bool RegHeaderBackend::generate(const std::string& outputDir) {
    std::string compatible = readCompatible();
    std::string guard      = makeGuard(compatible);
    std::string structName = makeStructName(compatible);
    std::string filename   = outputDir + "/"
                           + structName + ".h";

    std::ofstream file(filename);
    if (!file.is_open()) {
        llvm::errs() << "Cannot open: " << filename << "\n";
        return false;
    }

    emitFileHeader(file, compatible, guard);
    emitOffset(file);
    emitFields(file);
    emitAccessors(file);
    emitRegMapStruct(file);
    emitFileFooter(file, guard);

    file.close();
    llvm::outs() << "Generated: " << filename << "\n";
    return true;
}